### PR TITLE
Improve build

### PR DESCRIPTION
**Pull request by wridgeu**
Hi Marian,

as discussed, some minor adjustments to make it work for me. Properly setup the `ui5-tooling-modules` task, so that `xlsx` can be found where it's supposed to be, in the `resource` folder 
image

In addition I did some minor adjustments to the jQuery usage.

Let me know if I may have missed something in the setup that makes the use of UI5 tooling modules not necessary. I saw it in the dependencies and thought there was something missing. :D 

BR

### CODE REVIEW

**Review by marianfoo — CHANGES_REQUESTED** [review]
Hi Marco,
thanks for your input.
The one in Component.js makes sense.
Had copied there old code from a template, that's why there was still jquery in there.

But the build change is not necessary.
I haven't documented this yet, but the ui5-build.yaml is for publishing and ui5-build-files.yaml is explicitly without ui5-tooling-modules.
With [chokidar](https://github.com/marianfoo/ui5-cc-excelUpload/tree/main/dev), I do a build after each change so I don't have to make extra changes in the consuming app. 
The build with tooling-modules would only take much longer and nothing changes anyway, so I leave it out.

**Comment by wridgeu** [comment]
Hi,

>With [chokidar](https://github.com/marianfoo/ui5-cc-excelUpload/tree/main/dev), I do a build after each change so I don't have to make extra changes in the consuming app.
The build with tooling-modules would only take much longer and nothing changes anyway, so I leave it out.

I see, but how do you get the `xlsx` dependency bundled into your _resources_ folder in dist then? When I ran `build:watch` or `build:watchAll` that wasn't the case until I added the task to the ui5-build-files.yaml was I missing a step here? ^^

**Comment by wridgeu** [comment]
Makes totally sense to run that first and skip this step while watching for changes, wasn't sure how exactly you handled it at the moment. :) Will remove this part later today as soon as time allows it. ^^

**Comment by marianfoo** [comment]
no worries, i created a PR, could not commit directly
https://github.com/wridgeu/ui5-cc-excelUpload/pull/1

**Review by marianfoo — APPROVED** [review]

**Pull request merged**
